apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: alerts-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: KubevirtAlert is the Schema for the kubevirtalerts API
      displayName: Kubevirt Alert
      kind: KubevirtAlert
      name: kubevirtalerts.alerts.kubevirt.io
      version: v1alpha1
  description: doing stuff
  displayName: alerts operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - aaa
  links:
  - name: Alerts Operator
    url: https://alerts-operator.domain
  maturity: alpha
  provider:
    name: Aviv
  version: 0.0.0
